export const ADD_NEW_PAGE = "ADD_NEW_PAGE";
export const ADD_NEW_TAB = "ADD_NEW_TAB";
export const ADD_ELEMENT_TO_SYSTEM = "ADD_ELEMENT_TO_SYSTEM";
export const ADD_ROW_TO_TABLE = "ADD_ROW_TO_TABLE";
export const UPDATE_TABLE = "UPDATE_TABLE";
export const INSERT_ROW = "INSERT_ROW";
export const UPDATE_SCHEMA_TABLE = "UPDATE_SCHEMA_TABLE";
export const UPDATE_FORM = "UPDATE_FORM";
